# Generated by Django 3.0.3 on 2020-03-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extendflix', '0002_auto_20200303_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=400),
        ),
    ]
