# Generated by Django 3.0.3 on 2020-03-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extendflix', '0003_auto_20200303_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(blank='True', default='', max_length=8),
        ),
        migrations.AddField(
            model_name='movie',
            name='metacritic_rating',
            field=models.CharField(blank='True', default='', max_length=8),
        ),
        migrations.AddField(
            model_name='movie',
            name='rotten_tomatoes_rating',
            field=models.CharField(blank='True', default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank='True', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=8),
        ),
    ]
