# Generated by Django 3.0.3 on 2020-03-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extendflix', '0004_auto_20200304_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(blank='True', max_length=250),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.IntegerField(blank='True'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(blank='True', max_length=8),
        ),
    ]
