# Generated by Django 3.0.3 on 2020-03-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extendflix', '0005_auto_20200304_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(blank='True', max_length=300),
        ),
    ]
